CyrilDebon/catch_me

Gemfile
Gemfile.lock
app/controllers/stops_controller.rb
app/models/direction.rb
app/models/favorite.rb
app/models/line.rb
app/models/stop.rb
db/migrate/20190226095413_create_lines.rb
db/migrate/20190226103735_create_stops.rb
db/migrate/20190226103938_create_directions.rb
db/migrate/20190226105139_remove_name_and_user_stop_name_from_favorites.rb
db/migrate/20190226105324_add_stop_to_favorites.rb
db/schema.rb
db/seeds.rb
test/models/direction_test.rb
test/models/line_test.rb
test/models/stop_test.rb

On a créé les models et ajouter la gem "http"

creation of models and adding http gem

---

app/models/favorite.rb
app/models/line.rb
app/models/stop.rb
app/models/user.rb
db/migrate/20190226103735_create_stops.rb
db/migrate/20190226134055_fix_direction_fk.rb
db/schema.rb
db/seeds.rb

Création de LA PLUS GROSSE SEED DU WAGON EVER

Creation seed

---

app/assets/stylesheets/components/_circle-line-number.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_list-group-item.scss
app/assets/stylesheets/components/_list-item-link.scss
app/controllers/application_controller.rb
app/controllers/lines_controller.rb
app/controllers/stops_controller.rb
app/models/stop.rb
app/views/lines/index.html.erb
app/views/lines/show.html.erb
app/views/stops/show.html.erb
config/application.rb
db/seeds.rb
lib/tbm_api.rb

Désolé pour le push de gros dégue !

indexline-showline-showstop

---

app/controllers/stops_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_countdown.js
app/models/direction.rb
app/models/stop.rb
app/views/stops/show.html.erb
lib/passage.rb
package.json
yarn.lock

Countdown CRÉÉE !!!! en JS. Rien de bien complex

Create Countdown in JS

---

app/assets/stylesheets/components/_big-timer.scss
app/assets/stylesheets/components/_text.scss
app/views/stops/show.html.erb

J'ai réorganisé la show du stop. Elle est très minimale, assez stylé même mais j'arrive pas à regrouper les 3 éléments du milieu qui sont prochain passage, le chrono et le nom de l'arrêt.

organize stop show

---

app/views/shared/_flyout.html.erb
app/views/stops/show.html.erb

Ca fonctionne

---

Gemfile
Gemfile.lock
README.md
app/assets/stylesheets/components/_big-timer.scss
app/assets/stylesheets/components/_circle-transport-type.scss
app/assets/stylesheets/components/_html-body.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_stops.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_fonts.scss
app/models/line.rb
app/views/lines/index.html.erb
app/views/lines/show.html.erb
app/views/stops/show.html.erb
db/migrate/20190301104217_add_position_to_lines.rb
db/schema.rb
db/seeds.rb

Ajout du style dans les lines, et quelques modifs

add style and order of the lines

---

app/models/line.rb
app/views/layouts/application.html.erb

Add acts_as_list phrase dans le line model

add acts_as_list

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_star.scss
app/controllers/favorites_controller.rb
app/views/favorites/_actions.html.erb
app/views/favorites/_favorite.html.erb
app/views/favorites/create.js.erb
app/views/favorites/destroy.js.erb
app/views/shared/_flyout.html.erb
app/views/stops/show.html.erb
config/application.rb

Everything work without refresh

---

app/assets/stylesheets/components/_big-timer.scss
app/assets/stylesheets/components/_html-body.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/stops/show.html.erb

Le timer est bien positionné sur la show stop

fix the timer position on the stop show

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/views/layouts/application.html.erb
app/views/lines/index.html.erb
app/views/lines/show.html.erb
app/views/shared/_flyout.html.erb
app/views/shared/_navbar.html.erb
app/views/stops/show.html.erb

add a big wild fucking navbar BITCHES !!!

Add navbar

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/favorites_controller.rb
app/models/user.rb
app/views/favorites/_actions.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flyout.html.erb
app/views/stops/show.html.erb
db/migrate/20190304090933_add_devise_guests_to_users.rb
db/schema.rb

Added gem devise-guest
Added new guest-user to schema user
All visitor have "fake" account they can add/delete favorite
They can create a real account and keep their favorites
After all, the guest user session is destroy

added guest User in the app

---

app/views/favorites/_actions.html.erb
app/views/favorites/create.js.erb
app/views/stops/show.html.erb

correction from sylvain

---

app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

customize sign_in & sign_up pages,
sessions/new
registrations/new

customize-sign-in-sign-up-pages

---

app/assets/stylesheets/components/_flyout.scss

J'ai ajouté le z index sur le flyout le style de la map est déjà poushé normalement

add z-index flyout

---

app/assets/stylesheets/components/_map.scss

LES DEV LE DETESTENT !!!!! Clique si tu veux toi aussi connaitre une astuce pour Augmenter la taille de ton marqueur d'au moins 20 px !

Enlarge Marker

---

app/controllers/pages_controller.rb
app/javascript/plugins/init_mapbox.js
app/views/pages/home.html.erb
config/routes.rb

On a changé la root. Pas de home page finalement mais direct le lines index

change the home page to lines index

---

app/javascript/plugins/init_countdown.js
app/models/stop.rb
app/views/lines/show.html.erb
app/views/stops/show.html.erb
db/seeds.rb

Debuggage général avec Sylvain, changement stop destination.

debug lot of stuff

---

app/assets/stylesheets/components/_text.scss
app/views/stops/show.html.erb

Change la couleur des prochains passage, reste à quelques ajustement à faire sur l'espace entre les éléments.

change color of footer next passage

---

app/assets/stylesheets/components/_flyout.scss
app/assets/stylesheets/components/_stop-and-direction.scss
app/assets/stylesheets/components/_text.scss
app/views/stops/show.html.erb

J'ai ajouté le message qui informe le voyageur qu'en raison des perturbations du traffic, un bus peux arriver 30 secondes avant le nomre annoncé sur le compteur.

Add bus warning

---

app/views/shared/_flyout.html.erb

Style on Flyout on Aidez nous à améliorer Catch Me

---

app/javascript/plugins/init_countdown.js
app/views/stops/show.html.erb

J'ai ajouté un ID à la show pour voir si le type de transport qui arrive est un bus ou un tram.  Puis en fonction de l'ID, le compteur JS retire 10s(tram) ou 22s(bus) 
+ Si le compteur est = ou < à 0 il restera bloqué à 0 (il ne va pas compter -1,-2 etc...)

Add seconds on bus

---

app/javascript/plugins/init_countdown.js
app/views/reviews/index.html.erb
app/views/reviews/new.html.erb

J'ai mis en brouillon le review index + j'ai changé phrase formulaire

change phrase on form

---

app/javascript/plugins/init_countdown.js
app/views/stops/show.html.erb

Vérifie s'il y a des infos transmis par TBM 
Si aucune info ajoute du texte juste après "Prochain Passage"

Text stop show
